### ISSUE TITLE
Multiple "Card" main components are created when running more than once

### ISSUE THREAD

**Issue by clocky** [mamuso/figma-orgchart#3]
If you run the plugin multiple times (especially when fine tuning the JSON structure), a hidden main component called "Card" gets created over and over. It'd be nice to check if the "Card" component exists before creating a new instance of it.

Context: I found a layout I was happy with and wanted to tweak the card spacing, found the hidden card, but then had no idea which one was the real one.

**Comment by mamuso** [comment]
The plugin creates the card component on the fly, considering all the config options (colors, fonts, enabled fields, etc). Reusing it means that if you run the plugin a second time, it will not be able to apply new configuration options.

I have two potential solutions in mind:
- Use your suggestion of reusing the card component so that you can tweak it and use it in all the charts created on the same page. If you need to change the chart's configuration, you can use a different page of the doc, or delete the component.
- I use a timestamp as an ID to disambiguate multiple charts on the same page. I can add that same timestamp to the component's name to facilitate the association.

Reusing seems a better option.
